---
- name: "test"
  hosts: all
  gather_facts: no

tasks:
  - name: run show version on remote devices
    cisco.ioc.ios_command:
    commands: show version

  - name: run show version and check to see if output contains IOS
    cisco.ios.ios_command:
    commands: show version
    wait_for: result[0] contains IOS

  - name: run multiple commands on remote nodes
    cisco.ios.ios_command:
    commands:
    - show version
    - show interfaces

  - name: run multiple commands and evaluate the output
    cisco.ios.ios_command:
    commands:
    - show version
    - show interfaces
    wait_for:
    - result[0] contains IOS
    - result[1] contains vlan

  - name: run commands that require answering a prompt
    cisco.ios.ios_command:
    commands:
    - command: clear counters GigabitEthernet0/1
      prompt: Clear "show interface" counters on this interface [confirm]
      answer: y
    - command: clear counters GigabitEthernet0/2
      prompt: '[confirm]'
      answer: ''

