---
- name: Show Run - Save to Backups
  hosts: all
  gather_facts: false
  connection: local
  gather_facts: no

  tasks:
    - name: show run
      ios_command:
        commands:
        - show run
      register: config

    - name: save output to local directory
      copy:
        content: "{{ config.stdout | replace('\\n', '\n') }}"
        dest: "ios_backups/{{ inventory_hostname }}.ios"

    - name: save running to startup when modified
      ios_config:
        save_when: modified

